//go:build ignore

// Package freeagentapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package freeagentapi

const (
	Oauth2Scopes = "oauth2.Scopes"
)

// UploadABankStatementJSONBody defines parameters for UploadABankStatement.
type UploadABankStatementJSONBody struct {
	Statement *[]struct {
		Amount      *float32 `json:"amount,omitempty"`
		DatedOn     *string  `json:"dated_on,omitempty"`
		Description *string  `json:"description,omitempty"`
	} `json:"statement,omitempty"`
}

// UploadABankStatementParams defines parameters for UploadABankStatement.
type UploadABankStatementParams struct {
	BankAccount *string `form:"bank_account,omitempty" json:"bank_account,omitempty"`
}

// GetTheTrialBalanceSummaryParams defines parameters for GetTheTrialBalanceSummary.
type GetTheTrialBalanceSummaryParams struct {
	ToDate   *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	FromDate *string `form:"from_date,omitempty" json:"from_date,omitempty"`
}

// ListBankAccountsParams defines parameters for ListBankAccounts.
type ListBankAccountsParams struct {
	View *string `form:"view,omitempty" json:"view,omitempty"`
}

// CreateBankAccountJSONBody defines parameters for CreateBankAccount.
type CreateBankAccountJSONBody struct {
	BankAccount *struct {
		CreatedAt      *string `json:"created_at,omitempty"`
		IsPersonal     *bool   `json:"is_personal,omitempty"`
		Name           *string `json:"name,omitempty"`
		OpeningBalance *string `json:"opening_balance,omitempty"`
		Status         *string `json:"status,omitempty"`
		Type           *string `json:"type,omitempty"`
		UpdatedAt      *string `json:"updated_at,omitempty"`
	} `json:"bank_account,omitempty"`
}

// UpdateBankAccountJSONBody defines parameters for UpdateBankAccount.
type UpdateBankAccountJSONBody struct {
	BankAccount *struct {
		CreatedAt      *string `json:"created_at,omitempty"`
		IsPersonal     *bool   `json:"is_personal,omitempty"`
		Name           *string `json:"name,omitempty"`
		OpeningBalance *string `json:"opening_balance,omitempty"`
		Status         *string `json:"status,omitempty"`
		Type           *string `json:"type,omitempty"`
		UpdatedAt      *string `json:"updated_at,omitempty"`
	} `json:"bank_account,omitempty"`
}

// ListAllBankTransactionExplanationsParams defines parameters for ListAllBankTransactionExplanations.
type ListAllBankTransactionExplanationsParams struct {
	FromDate     *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate       *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	BankAccount  *string `form:"bank_account,omitempty" json:"bank_account,omitempty"`
}

// CreateABankTransactionExplanationJSONBody defines parameters for CreateABankTransactionExplanation.
type CreateABankTransactionExplanationJSONBody struct {
	BankTransactionExplanation *struct {
		Attachment *struct {
			ContentSrc  *string  `json:"content_src,omitempty"`
			ContentType *string  `json:"content_type,omitempty"`
			FileName    *string  `json:"file_name,omitempty"`
			FileSize    *float32 `json:"file_size,omitempty"`
			Url         *string  `json:"url,omitempty"`
		} `json:"attachment,omitempty"`
		BankAccount     *string `json:"bank_account,omitempty"`
		BankTransaction *string `json:"bank_transaction,omitempty"`
		Category        *string `json:"category,omitempty"`
		DatedOn         *string `json:"dated_on,omitempty"`
		Description     *string `json:"description,omitempty"`
		GrossValue      *string `json:"gross_value,omitempty"`
		Project         *string `json:"project,omitempty"`
		RebillFactor    *string `json:"rebill_factor,omitempty"`
		RebillType      *string `json:"rebill_type,omitempty"`
	} `json:"bank_transaction_explanation,omitempty"`
}

// UpdateABankTransactionExplanationJSONBody defines parameters for UpdateABankTransactionExplanation.
type UpdateABankTransactionExplanationJSONBody struct {
	BankTransactionExplanation *struct {
		Attachment *struct {
			ContentSrc  *string  `json:"content_src,omitempty"`
			ContentType *string  `json:"content_type,omitempty"`
			FileName    *string  `json:"file_name,omitempty"`
			FileSize    *float32 `json:"file_size,omitempty"`
			Url         *string  `json:"url,omitempty"`
		} `json:"attachment,omitempty"`
		BankAccount     *string `json:"bank_account,omitempty"`
		BankTransaction *string `json:"bank_transaction,omitempty"`
		Category        *string `json:"category,omitempty"`
		DatedOn         *string `json:"dated_on,omitempty"`
		Description     *string `json:"description,omitempty"`
		GrossValue      *string `json:"gross_value,omitempty"`
		Project         *string `json:"project,omitempty"`
		RebillFactor    *string `json:"rebill_factor,omitempty"`
		RebillType      *string `json:"rebill_type,omitempty"`
	} `json:"bank_transaction_explanation,omitempty"`
}

// DeleteABankTransactionExplanationJSONBody defines parameters for DeleteABankTransactionExplanation.
type DeleteABankTransactionExplanationJSONBody struct {
	BankTransactionExplanation *struct {
		Attachment *struct {
			ContentSrc  *string  `json:"content_src,omitempty"`
			ContentType *string  `json:"content_type,omitempty"`
			FileName    *string  `json:"file_name,omitempty"`
			FileSize    *float32 `json:"file_size,omitempty"`
			Url         *string  `json:"url,omitempty"`
		} `json:"attachment,omitempty"`
		BankAccount     *string `json:"bank_account,omitempty"`
		BankTransaction *string `json:"bank_transaction,omitempty"`
		Category        *string `json:"category,omitempty"`
		DatedOn         *string `json:"dated_on,omitempty"`
		Description     *string `json:"description,omitempty"`
		GrossValue      *string `json:"gross_value,omitempty"`
		Project         *string `json:"project,omitempty"`
		RebillFactor    *string `json:"rebill_factor,omitempty"`
		RebillType      *string `json:"rebill_type,omitempty"`
	} `json:"bank_transaction_explanation,omitempty"`
}

// ListAllBankTransactionsUnderACertainBankAccountParams defines parameters for ListAllBankTransactionsUnderACertainBankAccount.
type ListAllBankTransactionsUnderACertainBankAccountParams struct {
	BankAccount  *string `form:"bank_account,omitempty" json:"bank_account,omitempty"`
	FromDate     *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate       *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	View         *string `form:"view,omitempty" json:"view,omitempty"`
	LastUploaded *string `form:"last_uploaded,omitempty" json:"last_uploaded,omitempty"`
}

// ListBillItemsParams defines parameters for ListBillItems.
type ListBillItemsParams struct {
	Bill *string `form:"bill,omitempty" json:"bill,omitempty"`
}

// ListBillsParams defines parameters for ListBills.
type ListBillsParams struct {
	View         *string `form:"view,omitempty" json:"view,omitempty"`
	FromDate     *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate       *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	Contact      *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project      *string `form:"project,omitempty" json:"project,omitempty"`
}

// CreateBillJSONBody defines parameters for CreateBill.
type CreateBillJSONBody struct {
	Bill *struct {
		Attachment *struct {
			ContentType *string `json:"content_type,omitempty"`
			Data        *string `json:"data,omitempty"`
			Description *string `json:"description,omitempty"`
			FileName    *string `json:"file_name,omitempty"`
		} `json:"attachment,omitempty"`
		Category    *string `json:"category,omitempty"`
		Contact     *string `json:"contact,omitempty"`
		DatedOn     *string `json:"dated_on,omitempty"`
		DueOn       *string `json:"due_on,omitempty"`
		Reference   *string `json:"reference,omitempty"`
		SaleTaxRate *string `json:"sale_tax_rate,omitempty"`
		TotalValue  *string `json:"total_value,omitempty"`
	} `json:"bill,omitempty"`
}

// DeleteBillJSONBody defines parameters for DeleteBill.
type DeleteBillJSONBody struct {
	Bill *struct {
		Category    *string `json:"category,omitempty"`
		Contact     *string `json:"contact,omitempty"`
		DatedOn     *string `json:"dated_on,omitempty"`
		DueOn       *string `json:"due_on,omitempty"`
		Reference   *string `json:"reference,omitempty"`
		SaleTaxRate *string `json:"sale_tax_rate,omitempty"`
		TotalValue  *string `json:"total_value,omitempty"`
	} `json:"bill,omitempty"`
}

// UpdateBillJSONBody defines parameters for UpdateBill.
type UpdateBillJSONBody struct {
	Bill *struct {
		Category    *string `json:"category,omitempty"`
		Contact     *string `json:"contact,omitempty"`
		DatedOn     *string `json:"dated_on,omitempty"`
		DueOn       *string `json:"due_on,omitempty"`
		Reference   *string `json:"reference,omitempty"`
		SaleTaxRate *string `json:"sale_tax_rate,omitempty"`
		TotalValue  *string `json:"total_value,omitempty"`
	} `json:"bill,omitempty"`
}

// CreateCapitalAssetTypeJSONBody defines parameters for CreateCapitalAssetType.
type CreateCapitalAssetTypeJSONBody struct {
	CapitalAssetType *struct {
		Name *string `json:"name,omitempty"`
	} `json:"capital_asset_type,omitempty"`
}

// UpdateCapitalAssetTypeJSONBody defines parameters for UpdateCapitalAssetType.
type UpdateCapitalAssetTypeJSONBody struct {
	CapitalAssetType *struct {
		Name *string `json:"name,omitempty"`
	} `json:"capital_asset_type,omitempty"`
}

// ListAllCapitalAssetsParams defines parameters for ListAllCapitalAssets.
type ListAllCapitalAssetsParams struct {
	// IncludeHistory Retrieves information about events in the capital asset life cycle (such as purchase, depreciation, and disposal).
	IncludeHistory *string `form:"include_history,omitempty" json:"include_history,omitempty"`
}

// GetASingleCapitalAssetParams defines parameters for GetASingleCapitalAsset.
type GetASingleCapitalAssetParams struct {
	// IncludeHistory Retrieves information about events in the capital asset life cycle (such as purchase, depreciation, and disposal).
	IncludeHistory *string `form:"include_history,omitempty" json:"include_history,omitempty"`
}

// CashflowSummaryForAGivenDateRangeParams defines parameters for CashflowSummaryForAGivenDateRange.
type CashflowSummaryForAGivenDateRangeParams struct {
	FromDate *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate   *string `form:"to_date,omitempty" json:"to_date,omitempty"`
}

// CreateCategoryJSONBody defines parameters for CreateCategory.
type CreateCategoryJSONBody struct {
	Category *struct {
		AllowableForTax  *bool   `json:"allowable_for_tax,omitempty"`
		AutoSalesTaxRate *string `json:"auto_sales_tax_rate,omitempty"`
		CategoryGroup    *string `json:"category_group,omitempty"`
		Description      *string `json:"description,omitempty"`
		NominalCode      *string `json:"nominal_code,omitempty"`
		TaxReportingName *string `json:"tax_reporting_name,omitempty"`
	} `json:"category,omitempty"`
}

// UpdateCategoryJSONBody defines parameters for UpdateCategory.
type UpdateCategoryJSONBody struct {
	Category *struct {
		AllowableForTax  *bool   `json:"allowable_for_tax,omitempty"`
		AutoSalesTaxRate *string `json:"auto_sales_tax_rate,omitempty"`
		Description      *string `json:"description,omitempty"`
		NominalCode      *string `json:"nominal_code,omitempty"`
		TaxReportingName *string `json:"tax_reporting_name,omitempty"`
	} `json:"category,omitempty"`
}

// CreateContactJSONBody defines parameters for CreateContact.
type CreateContactJSONBody struct {
	Contact *struct {
		Email     *string `json:"email,omitempty"`
		FirstName *string `json:"first_name,omitempty"`
		LastName  *string `json:"last_name,omitempty"`
	} `json:"contact,omitempty"`
}

// DeleteContactJSONBody defines parameters for DeleteContact.
type DeleteContactJSONBody struct {
	Contact *struct {
		Email     *string `json:"email,omitempty"`
		FirstName *string `json:"first_name,omitempty"`
		LastName  *string `json:"last_name,omitempty"`
	} `json:"contact,omitempty"`
}

// UpdateContactJSONBody defines parameters for UpdateContact.
type UpdateContactJSONBody struct {
	Contact *struct {
		Country *string `json:"country,omitempty"`
	} `json:"contact,omitempty"`
}

// ListCreditNoteReconciliationsParams defines parameters for ListCreditNoteReconciliations.
type ListCreditNoteReconciliationsParams struct {
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	FromDate     *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate       *string `form:"to_date,omitempty" json:"to_date,omitempty"`
}

// CreateCreditNoteReconciliationJSONBody defines parameters for CreateCreditNoteReconciliation.
type CreateCreditNoteReconciliationJSONBody struct {
	CreditNoteReconciliation *struct {
		CreditNote   *string `json:"credit_note,omitempty"`
		Currency     *string `json:"currency,omitempty"`
		DatedOn      *string `json:"dated_on,omitempty"`
		ExchangeRate *string `json:"exchange_rate,omitempty"`
		GrossValue   *string `json:"gross_value,omitempty"`
		Invoice      *string `json:"invoice,omitempty"`
	} `json:"credit_note_reconciliation,omitempty"`
}

// DeleteCreditNoteReconciliationMultipartBody defines parameters for DeleteCreditNoteReconciliation.
type DeleteCreditNoteReconciliationMultipartBody struct {
	Empty *string `json:",omitempty"`
}

// UpdateCreditNoteReconciliationJSONBody defines parameters for UpdateCreditNoteReconciliation.
type UpdateCreditNoteReconciliationJSONBody struct {
	CreditNoteReconciliation *struct {
		GrossValue *string `json:"gross_value,omitempty"`
	} `json:"credit_note_reconciliation,omitempty"`
}

// ListCreditNotesParams defines parameters for ListCreditNotes.
type ListCreditNotesParams struct {
	Contact               *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project               *string `form:"project,omitempty" json:"project,omitempty"`
	Currency              *string `form:"currency,omitempty" json:"currency,omitempty"`
	View                  *string `form:"view,omitempty" json:"view,omitempty"`
	UpdatedSince          *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	Sort                  *string `form:"sort,omitempty" json:"sort,omitempty"`
	NestedCreditNoteItems *string `form:"nested_credit_note_items,omitempty" json:"nested_credit_note_items,omitempty"`
}

// CreateCreditNoteJSONBody defines parameters for CreateCreditNote.
type CreateCreditNoteJSONBody struct {
	CreditNote *struct {
		AlwaysShowBicAndIban *bool   `json:"always_show_bic_and_iban,omitempty"`
		Contact              *string `json:"contact,omitempty"`
		CreditNoteItems      *[]struct {
			Description *string  `json:"description,omitempty"`
			Price       *float32 `json:"price,omitempty"`
			Quantity    *float32 `json:"quantity,omitempty"`
		} `json:"credit_note_items,omitempty"`
		Currency           *string  `json:"currency,omitempty"`
		DatedOn            *string  `json:"dated_on,omitempty"`
		DueOn              *string  `json:"due_on,omitempty"`
		OmitHeader         *bool    `json:"omit_header,omitempty"`
		PaymentTermsInDays *float32 `json:"payment_terms_in_days,omitempty"`
	} `json:"credit_note,omitempty"`
}

// DeleteCreditNotesMultipartBody defines parameters for DeleteCreditNotes.
type DeleteCreditNotesMultipartBody = map[string]interface{}

// UpdateCreditNoteJSONBody defines parameters for UpdateCreditNote.
type UpdateCreditNoteJSONBody struct {
	CreditNote *struct {
		Comments        *string `json:"comments,omitempty"`
		CreditNoteItems *[]struct {
			Description *string `json:"description,omitempty"`
		} `json:"credit_note_items,omitempty"`
	} `json:"credit_note,omitempty"`
}

// SendCreditNoteEmailJSONBody defines parameters for SendCreditNoteEmail.
type SendCreditNoteEmailJSONBody struct {
	CreditNote *struct {
		Email *struct {
			Body    *string `json:"body,omitempty"`
			From    *string `json:"from,omitempty"`
			Subject *string `json:"subject,omitempty"`
			To      *string `json:"to,omitempty"`
		} `json:"email,omitempty"`
	} `json:"credit_note,omitempty"`
}

// CreateEstimateItemJSONBody defines parameters for CreateEstimateItem.
type CreateEstimateItemJSONBody struct {
	Estimate     *string `json:"estimate,omitempty"`
	EstimateItem *struct {
		Category      *string `json:"category,omitempty"`
		CreatedAt     *string `json:"created_at,omitempty"`
		Description   *string `json:"description,omitempty"`
		ItemType      *string `json:"item_type,omitempty"`
		Position      *string `json:"position,omitempty"`
		Price         *string `json:"price,omitempty"`
		Quantity      *string `json:"quantity,omitempty"`
		SalesTaxValue *string `json:"sales_tax_value,omitempty"`
		UpdatedAt     *string `json:"updated_at,omitempty"`
	} `json:"estimate_item,omitempty"`
}

// DeleteEstimateItemJSONBody defines parameters for DeleteEstimateItem.
type DeleteEstimateItemJSONBody struct {
	Estimate *struct {
		Contact      *string `json:"contact,omitempty"`
		Currency     *string `json:"currency,omitempty"`
		DatedOn      *string `json:"dated_on,omitempty"`
		DueOn        *string `json:"due_on,omitempty"`
		EcStatus     *string `json:"ec_status,omitempty"`
		EstimateType *string `json:"estimate_type,omitempty"`
		Notes        *string `json:"notes,omitempty"`
		Status       *string `json:"status,omitempty"`
	} `json:"estimate,omitempty"`
}

// UpdateEstimateItemJSONBody defines parameters for UpdateEstimateItem.
type UpdateEstimateItemJSONBody struct {
	EstimateItem *struct {
		Category      *string `json:"category,omitempty"`
		CreatedAt     *string `json:"created_at,omitempty"`
		Description   *string `json:"description,omitempty"`
		ItemType      *string `json:"item_type,omitempty"`
		Position      *string `json:"position,omitempty"`
		Price         *string `json:"price,omitempty"`
		Quantity      *string `json:"quantity,omitempty"`
		SalesTaxValue *string `json:"sales_tax_value,omitempty"`
		UpdatedAt     *string `json:"updated_at,omitempty"`
		Url           *string `json:"url,omitempty"`
	} `json:"estimate_item,omitempty"`
}

// ListEstimatesParams defines parameters for ListEstimates.
type ListEstimatesParams struct {
	View                *string `form:"view,omitempty" json:"view,omitempty"`
	FromDate            *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate              *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	UpdatedSince        *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	NestedEstimateItems *string `form:"nested_estimate_items,omitempty" json:"nested_estimate_items,omitempty"`
	Contact             *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project             *string `form:"project,omitempty" json:"project,omitempty"`
	Invoice             *string `form:"invoice,omitempty" json:"invoice,omitempty"`
}

// CreateEstimateJSONBody defines parameters for CreateEstimate.
type CreateEstimateJSONBody struct {
	Estimate *struct {
		Contact      *string `json:"contact,omitempty"`
		Currency     *string `json:"currency,omitempty"`
		DatedOn      *string `json:"dated_on,omitempty"`
		DueOn        *string `json:"due_on,omitempty"`
		EstimateType *string `json:"estimate_type,omitempty"`
		Status       *string `json:"status,omitempty"`
	} `json:"estimate,omitempty"`
}

// DeleteEstimateJSONBody defines parameters for DeleteEstimate.
type DeleteEstimateJSONBody struct {
	Estimate *struct {
		Contact      *string `json:"contact,omitempty"`
		Currency     *string `json:"currency,omitempty"`
		DatedOn      *string `json:"dated_on,omitempty"`
		DueOn        *string `json:"due_on,omitempty"`
		EcStatus     *string `json:"ec_status,omitempty"`
		EstimateType *string `json:"estimate_type,omitempty"`
		Notes        *string `json:"notes,omitempty"`
		Status       *string `json:"status,omitempty"`
	} `json:"estimate,omitempty"`
}

// UpdateEstimateJSONBody defines parameters for UpdateEstimate.
type UpdateEstimateJSONBody struct {
	Estimate *struct {
		Notes *string `json:"notes,omitempty"`
	} `json:"estimate,omitempty"`
}

// CreateExpenseJSONBody defines parameters for CreateExpense.
type CreateExpenseJSONBody struct {
	Expenses *[]struct {
		Category             *string `json:"category,omitempty"`
		CreatedAt            *string `json:"created_at,omitempty"`
		DatedOn              *string `json:"dated_on,omitempty"`
		Description          *string `json:"description,omitempty"`
		GrossValue           *string `json:"gross_value,omitempty"`
		ManualSalesTaxAmount *string `json:"manual_sales_tax_amount,omitempty"`
		SalesTaxRate         *string `json:"sales_tax_rate,omitempty"`
		UpdatedAt            *string `json:"updated_at,omitempty"`
		User                 *string `json:"user,omitempty"`
	} `json:"expenses,omitempty"`
}

// DeleteExpenseMultipartBody defines parameters for DeleteExpense.
type DeleteExpenseMultipartBody = map[string]interface{}

// CreateInvoiceItemJSONBody defines parameters for CreateInvoiceItem.
type CreateInvoiceItemJSONBody struct {
	Invoice     *string `json:"invoice,omitempty"`
	InvoiceItem *struct {
		Description *string  `json:"description,omitempty"`
		ItemType    *string  `json:"item_type,omitempty"`
		Price       *float32 `json:"price,omitempty"`
		Quantity    *float32 `json:"quantity,omitempty"`
	} `json:"invoice_item,omitempty"`
}

// ListInvoicesParams defines parameters for ListInvoices.
type ListInvoicesParams struct {
	NestedInvoiceItems *string `form:"nested_invoice_items,omitempty" json:"nested_invoice_items,omitempty"`
	Contact            *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project            *string `form:"project,omitempty" json:"project,omitempty"`
	Currency           *string `form:"currency,omitempty" json:"currency,omitempty"`
	View               *string `form:"view,omitempty" json:"view,omitempty"`
	UpdatedSince       *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	Sort               *string `form:"sort,omitempty" json:"sort,omitempty"`
}

// CreateInvoiceJSONBody defines parameters for CreateInvoice.
type CreateInvoiceJSONBody struct {
	Invoice *struct {
		AlwaysShowBicAndIban *bool    `json:"always_show_bic_and_iban,omitempty"`
		Contact              *string  `json:"contact,omitempty"`
		Currency             *string  `json:"currency,omitempty"`
		DatedOn              *string  `json:"dated_on,omitempty"`
		DueOn                *string  `json:"due_on,omitempty"`
		OmitHeader           *bool    `json:"omit_header,omitempty"`
		PaymentTermsInDays   *float32 `json:"payment_terms_in_days,omitempty"`
	} `json:"invoice,omitempty"`
}

// DeleteInvoiceMultipartBody defines parameters for DeleteInvoice.
type DeleteInvoiceMultipartBody = map[string]interface{}

// UpdateInvoiceJSONBody defines parameters for UpdateInvoice.
type UpdateInvoiceJSONBody struct {
	Invoice *struct {
		Notes *string `json:"notes,omitempty"`
	} `json:"invoice,omitempty"`
}

// TakePaymentUsingGocardlessDirectDebitMandateTextBody defines parameters for TakePaymentUsingGocardlessDirectDebitMandate.
type TakePaymentUsingGocardlessDirectDebitMandateTextBody interface{}

// SendInvoiceEmailJSONBody defines parameters for SendInvoiceEmail.
type SendInvoiceEmailJSONBody struct {
	Invoice *struct {
		Email *struct {
			Body    *string `json:"body,omitempty"`
			From    *string `json:"from,omitempty"`
			Subject *string `json:"subject,omitempty"`
			To      *string `json:"to,omitempty"`
		} `json:"email,omitempty"`
	} `json:"invoice,omitempty"`
}

// ListAllJournalSetsParams defines parameters for ListAllJournalSets.
type ListAllJournalSetsParams struct {
	ToDate   *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	FromDate *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	Tag      *string `form:"tag,omitempty" json:"tag,omitempty"`
}

// CreateAJournalSetJSONBody defines parameters for CreateAJournalSet.
type CreateAJournalSetJSONBody struct {
	JournalSet *struct {
		DatedOn        *string `json:"dated_on,omitempty"`
		Description    *string `json:"description,omitempty"`
		JournalEntries *[]struct {
			Category    *string `json:"category,omitempty"`
			DebitValue  *string `json:"debit_value,omitempty"`
			Description *string `json:"description,omitempty"`
			User        *string `json:"user,omitempty"`
		} `json:"journal_entries,omitempty"`
		Tag *string `json:"tag,omitempty"`
	} `json:"journal_set,omitempty"`
}

// UpdateAJournalSetJSONBody defines parameters for UpdateAJournalSet.
type UpdateAJournalSetJSONBody struct {
	JournalSet *struct {
		DatedOn        *string `json:"dated_on,omitempty"`
		Description    *string `json:"description,omitempty"`
		JournalEntries *[]struct {
			Category    *string `json:"category,omitempty"`
			DebitValue  *string `json:"debit_value,omitempty"`
			Description *string `json:"description,omitempty"`
			Url         *string `json:"url,omitempty"`
			User        *string `json:"user,omitempty"`
		} `json:"journal_entries,omitempty"`
		Tag *string `json:"tag,omitempty"`
		Url *string `json:"url,omitempty"`
	} `json:"journal_set,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// CreateANoteJSONBody defines parameters for CreateANote.
type CreateANoteJSONBody struct {
	Note *struct {
		Author    *string `json:"author,omitempty"`
		CreatedAt *string `json:"created_at,omitempty"`
		Note      *string `json:"note,omitempty"`
		ParentUrl *string `json:"parent_url,omitempty"`
		UpdatedAt *string `json:"updated_at,omitempty"`
	} `json:"note,omitempty"`
}

// CreateANoteParams defines parameters for CreateANote.
type CreateANoteParams struct {
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// UpdateANoteJSONBody defines parameters for UpdateANote.
type UpdateANoteJSONBody struct {
	Note *struct {
		Author    *string `json:"author,omitempty"`
		CreatedAt *string `json:"created_at,omitempty"`
		Note      *string `json:"note,omitempty"`
		ParentUrl *string `json:"parent_url,omitempty"`
		UpdatedAt *string `json:"updated_at,omitempty"`
	} `json:"note,omitempty"`
}

// ListAllProfilesForAGivenTaxYearParams defines parameters for ListAllProfilesForAGivenTaxYear.
type ListAllProfilesForAGivenTaxYearParams struct {
	User *string `form:"user,omitempty" json:"user,omitempty"`
}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`

	// Nested Retrieves contact's details as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// CreateProjectJSONBody defines parameters for CreateProject.
type CreateProjectJSONBody struct {
	Project *struct {
		BillingPeriod              *string  `json:"billing_period,omitempty"`
		Budget                     *float32 `json:"budget,omitempty"`
		BudgetUnits                *string  `json:"budget_units,omitempty"`
		Contact                    *string  `json:"contact,omitempty"`
		Currency                   *string  `json:"currency,omitempty"`
		EndsOn                     *string  `json:"ends_on,omitempty"`
		HoursPerDay                *float32 `json:"hours_per_day,omitempty"`
		IsIr35                     *bool    `json:"is_ir35,omitempty"`
		Name                       *string  `json:"name,omitempty"`
		NormalBillingRate          *float32 `json:"normal_billing_rate,omitempty"`
		StartsOn                   *string  `json:"starts_on,omitempty"`
		Status                     *string  `json:"status,omitempty"`
		UsesProjectInvoiceSequence *bool    `json:"uses_project_invoice_sequence,omitempty"`
	} `json:"project,omitempty"`
}

// DeleteProjectMultipartBody defines parameters for DeleteProject.
type DeleteProjectMultipartBody = map[string]interface{}

// ShowProjectParams defines parameters for ShowProject.
type ShowProjectParams struct {
	// Nested Retrieves contact's details as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	Project *struct {
		Name *string `json:"name,omitempty"`
	} `json:"project,omitempty"`
}

// CreateANewPropertyJSONBody defines parameters for CreateANewProperty.
type CreateANewPropertyJSONBody struct {
	Property *struct {
		Address1 *string `json:"address1,omitempty"`
		Country  *string `json:"country,omitempty"`
		Region   *string `json:"region,omitempty"`
		Town     *string `json:"town,omitempty"`
	} `json:"property,omitempty"`
}

// UpdateAPropertyJSONBody defines parameters for UpdateAProperty.
type UpdateAPropertyJSONBody struct {
	Property *struct {
		Address2 *string `json:"address2,omitempty"`
	} `json:"property,omitempty"`
}

// ListAllRecurringInvoicesParams defines parameters for ListAllRecurringInvoices.
type ListAllRecurringInvoicesParams struct {
	View    *string `form:"view,omitempty" json:"view,omitempty"`
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`
}

// CreateASalesTaxPeriodJSONBody defines parameters for CreateASalesTaxPeriod.
type CreateASalesTaxPeriodJSONBody struct {
	SalesTaxPeriod *struct {
		EffectiveDate              *string `json:"effective_date,omitempty"`
		SalesTaxIsValueAdded       *bool   `json:"sales_tax_is_value_added,omitempty"`
		SalesTaxName               *string `json:"sales_tax_name,omitempty"`
		SalesTaxRate1              *string `json:"sales_tax_rate_1,omitempty"`
		SalesTaxRate2              *string `json:"sales_tax_rate_2,omitempty"`
		SalesTaxRate3              *string `json:"sales_tax_rate_3,omitempty"`
		SalesTaxRegistrationNumber *string `json:"sales_tax_registration_number,omitempty"`
		SalesTaxRegistrationStatus *string `json:"sales_tax_registration_status,omitempty"`
		SecondSalesTaxIsCompound   *bool   `json:"second_sales_tax_is_compound,omitempty"`
		SecondSalesTaxName         *string `json:"second_sales_tax_name,omitempty"`
		SecondSalesTaxRate1        *string `json:"second_sales_tax_rate_1,omitempty"`
		SecondSalesTaxRate2        *string `json:"second_sales_tax_rate_2,omitempty"`
		SecondSalesTaxRate3        *string `json:"second_sales_tax_rate_3,omitempty"`
	} `json:"sales_tax_period,omitempty"`
}

// UpdateASalesTaxPeriodJSONBody defines parameters for UpdateASalesTaxPeriod.
type UpdateASalesTaxPeriodJSONBody struct {
	SalesTaxPeriod *struct {
		EffectiveDate              *string `json:"effective_date,omitempty"`
		SalesTaxIsValueAdded       *bool   `json:"sales_tax_is_value_added,omitempty"`
		SalesTaxName               *string `json:"sales_tax_name,omitempty"`
		SalesTaxRate1              *string `json:"sales_tax_rate_1,omitempty"`
		SalesTaxRate2              *string `json:"sales_tax_rate_2,omitempty"`
		SalesTaxRate3              *string `json:"sales_tax_rate_3,omitempty"`
		SalesTaxRegistrationNumber *string `json:"sales_tax_registration_number,omitempty"`
		SalesTaxRegistrationStatus *string `json:"sales_tax_registration_status,omitempty"`
		SecondSalesTaxIsCompound   *bool   `json:"second_sales_tax_is_compound,omitempty"`
		SecondSalesTaxName         *string `json:"second_sales_tax_name,omitempty"`
		SecondSalesTaxRate1        *string `json:"second_sales_tax_rate_1,omitempty"`
		SecondSalesTaxRate2        *string `json:"second_sales_tax_rate_2,omitempty"`
		SecondSalesTaxRate3        *string `json:"second_sales_tax_rate_3,omitempty"`
	} `json:"sales_tax_period,omitempty"`
}

// ListAllStockItemsParams defines parameters for ListAllStockItems.
type ListAllStockItemsParams struct {
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`
}

// ListAllTasksParams defines parameters for ListAllTasks.
type ListAllTasksParams struct {
	View         *string `form:"view,omitempty" json:"view,omitempty"`
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	Project      *string `form:"project,omitempty" json:"project,omitempty"`
}

// CreateATaskUnderACertainProjectJSONBody defines parameters for CreateATaskUnderACertainProject.
type CreateATaskUnderACertainProjectJSONBody struct {
	Task *struct {
		BillingPeriod *string `json:"billing_period,omitempty"`
		BillingRate   *string `json:"billing_rate,omitempty"`
		IsBillable    *bool   `json:"is_billable,omitempty"`
		Name          *string `json:"name,omitempty"`
		Status        *string `json:"status,omitempty"`
	} `json:"task,omitempty"`
}

// CreateATaskUnderACertainProjectParams defines parameters for CreateATaskUnderACertainProject.
type CreateATaskUnderACertainProjectParams struct {
	Project *string `form:"project,omitempty" json:"project,omitempty"`
}

// DeleteTaskMultipartBody defines parameters for DeleteTask.
type DeleteTaskMultipartBody = map[string]interface{}

// UpdateATaskJSONBody defines parameters for UpdateATask.
type UpdateATaskJSONBody struct {
	Task *struct {
		BillingPeriod *string `json:"billing_period,omitempty"`
		BillingRate   *string `json:"billing_rate,omitempty"`
		IsBillable    *bool   `json:"is_billable,omitempty"`
		Name          *string `json:"name,omitempty"`
		Status        *string `json:"status,omitempty"`
	} `json:"task,omitempty"`
}

// ListAllTimeslipsParams defines parameters for ListAllTimeslips.
type ListAllTimeslipsParams struct {
	View         *string `form:"view,omitempty" json:"view,omitempty"`
	FromDate     *string `form:"from_date,omitempty" json:"from_date,omitempty"`
	ToDate       *string `form:"to_date,omitempty" json:"to_date,omitempty"`
	UpdatedSince *string `form:"updated_since,omitempty" json:"updated_since,omitempty"`
	User         *string `form:"user,omitempty" json:"user,omitempty"`
	Task         *string `form:"task,omitempty" json:"task,omitempty"`
	Project      *string `form:"project,omitempty" json:"project,omitempty"`

	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// CreateATimeslipJSONBody defines parameters for CreateATimeslip.
type CreateATimeslipJSONBody struct {
	Timeslip *struct {
		CreatedAt *string `json:"created_at,omitempty"`
		DatedOn   *string `json:"dated_on,omitempty"`
		Hours     *string `json:"hours,omitempty"`
		Project   *string `json:"project,omitempty"`
		Task      *string `json:"task,omitempty"`
		UpdatedAt *string `json:"updated_at,omitempty"`
		User      *string `json:"user,omitempty"`
	} `json:"timeslip,omitempty"`
}

// CreateATimeslipParams defines parameters for CreateATimeslip.
type CreateATimeslipParams struct {
	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// DeleteATimeslipMultipartBody defines parameters for DeleteATimeslip.
type DeleteATimeslipMultipartBody = map[string]interface{}

// GetASingleTimeslipParams defines parameters for GetASingleTimeslip.
type GetASingleTimeslipParams struct {
	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// UpdateATimeslipJSONBody defines parameters for UpdateATimeslip.
type UpdateATimeslipJSONBody struct {
	Timeslip *struct {
		DatedOn *string `json:"dated_on,omitempty"`
		Hours   *string `json:"hours,omitempty"`
		Project *string `json:"project,omitempty"`
		Task    *string `json:"task,omitempty"`
		User    *string `json:"user,omitempty"`
	} `json:"timeslip,omitempty"`
}

// UpdateATimeslipParams defines parameters for UpdateATimeslip.
type UpdateATimeslipParams struct {
	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// StopATimerMultipartBody defines parameters for StopATimer.
type StopATimerMultipartBody = map[string]interface{}

// StopATimerParams defines parameters for StopATimer.
type StopATimerParams struct {
	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// StartATimerJSONBody defines parameters for StartATimer.
type StartATimerJSONBody struct {
	Timeslip *struct {
		CreatedAt *string `json:"created_at,omitempty"`
		DatedOn   *string `json:"dated_on,omitempty"`
		Hours     *string `json:"hours,omitempty"`
		Project   *string `json:"project,omitempty"`
		Task      *string `json:"task,omitempty"`
		UpdatedAt *string `json:"updated_at,omitempty"`
		User      *string `json:"user,omitempty"`
	} `json:"timeslip,omitempty"`
}

// StartATimerParams defines parameters for StartATimer.
type StartATimerParams struct {
	// Nested Retrieves full details of resources associated with the timeslip(s) - such as user, project, task - as nested JSON objects rather than URL references.
	Nested *string `form:"nested,omitempty" json:"nested,omitempty"`
}

// RefreshAccessTokenFormdataBody defines parameters for RefreshAccessToken.
type RefreshAccessTokenFormdataBody struct {
	ClientId     *string `form:"client_id,omitempty" json:"client_id,omitempty"`
	ClientSecret *string `form:"client_secret,omitempty" json:"client_secret,omitempty"`
	GrantType    *string `form:"grant_type,omitempty" json:"grant_type,omitempty"`
	RefreshToken *string `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
}

// CreateAUserJSONBody defines parameters for CreateAUser.
type CreateAUserJSONBody struct {
	User *struct {
		Email              *string  `json:"email,omitempty"`
		FirstName          *string  `json:"first_name,omitempty"`
		LastName           *string  `json:"last_name,omitempty"`
		NiNumber           *string  `json:"ni_number,omitempty"`
		OpeningMileage     *float32 `json:"opening_mileage,omitempty"`
		PermissionLevel    *float32 `json:"permission_level,omitempty"`
		Role               *string  `json:"role,omitempty"`
		UniqueTaxReference *string  `json:"unique_tax_reference,omitempty"`
	} `json:"user,omitempty"`
}

// UpdateAUserJSONBody defines parameters for UpdateAUser.
type UpdateAUserJSONBody struct {
	User *struct {
		Email              *string  `json:"email,omitempty"`
		FirstName          *string  `json:"first_name,omitempty"`
		LastName           *string  `json:"last_name,omitempty"`
		NiNumber           *string  `json:"ni_number,omitempty"`
		OpeningMileage     *float32 `json:"opening_mileage,omitempty"`
		PermissionLevel    *float32 `json:"permission_level,omitempty"`
		Role               *string  `json:"role,omitempty"`
		UniqueTaxReference *string  `json:"unique_tax_reference,omitempty"`
	} `json:"user,omitempty"`
}

// UploadABankStatementJSONRequestBody defines body for UploadABankStatement for application/json ContentType.
type UploadABankStatementJSONRequestBody UploadABankStatementJSONBody

// CreateBankAccountJSONRequestBody defines body for CreateBankAccount for application/json ContentType.
type CreateBankAccountJSONRequestBody CreateBankAccountJSONBody

// UpdateBankAccountJSONRequestBody defines body for UpdateBankAccount for application/json ContentType.
type UpdateBankAccountJSONRequestBody UpdateBankAccountJSONBody

// CreateABankTransactionExplanationJSONRequestBody defines body for CreateABankTransactionExplanation for application/json ContentType.
type CreateABankTransactionExplanationJSONRequestBody CreateABankTransactionExplanationJSONBody

// UpdateABankTransactionExplanationJSONRequestBody defines body for UpdateABankTransactionExplanation for application/json ContentType.
type UpdateABankTransactionExplanationJSONRequestBody UpdateABankTransactionExplanationJSONBody

// DeleteABankTransactionExplanationJSONRequestBody defines body for DeleteABankTransactionExplanation for application/json ContentType.
type DeleteABankTransactionExplanationJSONRequestBody DeleteABankTransactionExplanationJSONBody

// CreateBillJSONRequestBody defines body for CreateBill for application/json ContentType.
type CreateBillJSONRequestBody CreateBillJSONBody

// DeleteBillJSONRequestBody defines body for DeleteBill for application/json ContentType.
type DeleteBillJSONRequestBody DeleteBillJSONBody

// UpdateBillJSONRequestBody defines body for UpdateBill for application/json ContentType.
type UpdateBillJSONRequestBody UpdateBillJSONBody

// CreateCapitalAssetTypeJSONRequestBody defines body for CreateCapitalAssetType for application/json ContentType.
type CreateCapitalAssetTypeJSONRequestBody CreateCapitalAssetTypeJSONBody

// UpdateCapitalAssetTypeJSONRequestBody defines body for UpdateCapitalAssetType for application/json ContentType.
type UpdateCapitalAssetTypeJSONRequestBody UpdateCapitalAssetTypeJSONBody

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody CreateCategoryJSONBody

// UpdateCategoryJSONRequestBody defines body for UpdateCategory for application/json ContentType.
type UpdateCategoryJSONRequestBody UpdateCategoryJSONBody

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody CreateContactJSONBody

// DeleteContactJSONRequestBody defines body for DeleteContact for application/json ContentType.
type DeleteContactJSONRequestBody DeleteContactJSONBody

// UpdateContactJSONRequestBody defines body for UpdateContact for application/json ContentType.
type UpdateContactJSONRequestBody UpdateContactJSONBody

// CreateCreditNoteReconciliationJSONRequestBody defines body for CreateCreditNoteReconciliation for application/json ContentType.
type CreateCreditNoteReconciliationJSONRequestBody CreateCreditNoteReconciliationJSONBody

// DeleteCreditNoteReconciliationMultipartRequestBody defines body for DeleteCreditNoteReconciliation for multipart/form-data ContentType.
type DeleteCreditNoteReconciliationMultipartRequestBody DeleteCreditNoteReconciliationMultipartBody

// UpdateCreditNoteReconciliationJSONRequestBody defines body for UpdateCreditNoteReconciliation for application/json ContentType.
type UpdateCreditNoteReconciliationJSONRequestBody UpdateCreditNoteReconciliationJSONBody

// CreateCreditNoteJSONRequestBody defines body for CreateCreditNote for application/json ContentType.
type CreateCreditNoteJSONRequestBody CreateCreditNoteJSONBody

// DeleteCreditNotesMultipartRequestBody defines body for DeleteCreditNotes for multipart/form-data ContentType.
type DeleteCreditNotesMultipartRequestBody = DeleteCreditNotesMultipartBody

// UpdateCreditNoteJSONRequestBody defines body for UpdateCreditNote for application/json ContentType.
type UpdateCreditNoteJSONRequestBody UpdateCreditNoteJSONBody

// SendCreditNoteEmailJSONRequestBody defines body for SendCreditNoteEmail for application/json ContentType.
type SendCreditNoteEmailJSONRequestBody SendCreditNoteEmailJSONBody

// CreateEstimateItemJSONRequestBody defines body for CreateEstimateItem for application/json ContentType.
type CreateEstimateItemJSONRequestBody CreateEstimateItemJSONBody

// DeleteEstimateItemJSONRequestBody defines body for DeleteEstimateItem for application/json ContentType.
type DeleteEstimateItemJSONRequestBody DeleteEstimateItemJSONBody

// UpdateEstimateItemJSONRequestBody defines body for UpdateEstimateItem for application/json ContentType.
type UpdateEstimateItemJSONRequestBody UpdateEstimateItemJSONBody

// CreateEstimateJSONRequestBody defines body for CreateEstimate for application/json ContentType.
type CreateEstimateJSONRequestBody CreateEstimateJSONBody

// DeleteEstimateJSONRequestBody defines body for DeleteEstimate for application/json ContentType.
type DeleteEstimateJSONRequestBody DeleteEstimateJSONBody

// UpdateEstimateJSONRequestBody defines body for UpdateEstimate for application/json ContentType.
type UpdateEstimateJSONRequestBody UpdateEstimateJSONBody

// CreateExpenseJSONRequestBody defines body for CreateExpense for application/json ContentType.
type CreateExpenseJSONRequestBody CreateExpenseJSONBody

// DeleteExpenseMultipartRequestBody defines body for DeleteExpense for multipart/form-data ContentType.
type DeleteExpenseMultipartRequestBody = DeleteExpenseMultipartBody

// CreateInvoiceItemJSONRequestBody defines body for CreateInvoiceItem for application/json ContentType.
type CreateInvoiceItemJSONRequestBody CreateInvoiceItemJSONBody

// CreateInvoiceJSONRequestBody defines body for CreateInvoice for application/json ContentType.
type CreateInvoiceJSONRequestBody CreateInvoiceJSONBody

// DeleteInvoiceMultipartRequestBody defines body for DeleteInvoice for multipart/form-data ContentType.
type DeleteInvoiceMultipartRequestBody = DeleteInvoiceMultipartBody

// UpdateInvoiceJSONRequestBody defines body for UpdateInvoice for application/json ContentType.
type UpdateInvoiceJSONRequestBody UpdateInvoiceJSONBody

// TakePaymentUsingGocardlessDirectDebitMandateTextRequestBody defines body for TakePaymentUsingGocardlessDirectDebitMandate for text/plain ContentType.
type TakePaymentUsingGocardlessDirectDebitMandateTextRequestBody TakePaymentUsingGocardlessDirectDebitMandateTextBody

// SendInvoiceEmailJSONRequestBody defines body for SendInvoiceEmail for application/json ContentType.
type SendInvoiceEmailJSONRequestBody SendInvoiceEmailJSONBody

// CreateAJournalSetJSONRequestBody defines body for CreateAJournalSet for application/json ContentType.
type CreateAJournalSetJSONRequestBody CreateAJournalSetJSONBody

// UpdateAJournalSetJSONRequestBody defines body for UpdateAJournalSet for application/json ContentType.
type UpdateAJournalSetJSONRequestBody UpdateAJournalSetJSONBody

// CreateANoteJSONRequestBody defines body for CreateANote for application/json ContentType.
type CreateANoteJSONRequestBody CreateANoteJSONBody

// UpdateANoteJSONRequestBody defines body for UpdateANote for application/json ContentType.
type UpdateANoteJSONRequestBody UpdateANoteJSONBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody CreateProjectJSONBody

// DeleteProjectMultipartRequestBody defines body for DeleteProject for multipart/form-data ContentType.
type DeleteProjectMultipartRequestBody = DeleteProjectMultipartBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody

// CreateANewPropertyJSONRequestBody defines body for CreateANewProperty for application/json ContentType.
type CreateANewPropertyJSONRequestBody CreateANewPropertyJSONBody

// UpdateAPropertyJSONRequestBody defines body for UpdateAProperty for application/json ContentType.
type UpdateAPropertyJSONRequestBody UpdateAPropertyJSONBody

// CreateASalesTaxPeriodJSONRequestBody defines body for CreateASalesTaxPeriod for application/json ContentType.
type CreateASalesTaxPeriodJSONRequestBody CreateASalesTaxPeriodJSONBody

// UpdateASalesTaxPeriodJSONRequestBody defines body for UpdateASalesTaxPeriod for application/json ContentType.
type UpdateASalesTaxPeriodJSONRequestBody UpdateASalesTaxPeriodJSONBody

// CreateATaskUnderACertainProjectJSONRequestBody defines body for CreateATaskUnderACertainProject for application/json ContentType.
type CreateATaskUnderACertainProjectJSONRequestBody CreateATaskUnderACertainProjectJSONBody

// DeleteTaskMultipartRequestBody defines body for DeleteTask for multipart/form-data ContentType.
type DeleteTaskMultipartRequestBody = DeleteTaskMultipartBody

// UpdateATaskJSONRequestBody defines body for UpdateATask for application/json ContentType.
type UpdateATaskJSONRequestBody UpdateATaskJSONBody

// CreateATimeslipJSONRequestBody defines body for CreateATimeslip for application/json ContentType.
type CreateATimeslipJSONRequestBody CreateATimeslipJSONBody

// DeleteATimeslipMultipartRequestBody defines body for DeleteATimeslip for multipart/form-data ContentType.
type DeleteATimeslipMultipartRequestBody = DeleteATimeslipMultipartBody

// UpdateATimeslipJSONRequestBody defines body for UpdateATimeslip for application/json ContentType.
type UpdateATimeslipJSONRequestBody UpdateATimeslipJSONBody

// StopATimerMultipartRequestBody defines body for StopATimer for multipart/form-data ContentType.
type StopATimerMultipartRequestBody = StopATimerMultipartBody

// StartATimerJSONRequestBody defines body for StartATimer for application/json ContentType.
type StartATimerJSONRequestBody StartATimerJSONBody

// RefreshAccessTokenFormdataRequestBody defines body for RefreshAccessToken for application/x-www-form-urlencoded ContentType.
type RefreshAccessTokenFormdataRequestBody RefreshAccessTokenFormdataBody

// CreateAUserJSONRequestBody defines body for CreateAUser for application/json ContentType.
type CreateAUserJSONRequestBody CreateAUserJSONBody

// UpdateAUserJSONRequestBody defines body for UpdateAUser for application/json ContentType.
type UpdateAUserJSONRequestBody UpdateAUserJSONBody
